### ISSUE TITLE
Investigate Python script to pre-parse Redfish JSON schemas

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/oneview-redfish-toolkit#10]
In order to use the Redfish JSON schemas to create objects or classes we need a script to pre-parse the existing JSON schemas.  The script will need to:

1)	Resolve all $ref pointers
2)	Reduce the anyOf/oneOf keywords to single references and resolve the references

**Comment by ffdarkpenguin** [comment]
@danielreed : the library https://github.com/Julian/jsonschema has a validate function that takes a json and a schema. It resolves all $ref and all the keywords listed on item 2. This is the lib we are going to use in the project

**Comment by danielreed** [comment]
That looks great for performing validation but I don't see how the library can be used to create objects from the JSON schema.

**Comment by ricardoas** [comment]
It just solves the validation problem, @danielreed! We agreed to work creating python classes from scratch, right? At least while we search for a loader that can solve this problems...

**Comment by danielreed** [comment]
Yes @ricardoas that's what I remember too.  Create the classes from scratch until we can find a better way.

**Comment by danielreed** [comment]
Going to close this.  Don't have the time or resources to use this approach.
