### ISSUE TITLE
Implement NetworkInterfaceCollection

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#119]
As oneview-redfish-user, I access "/redfish/v1/Systems/<server_hardware_uuid>/NetworkInterfaces" and receive the collection of NetworkInterface objects associated with this OneView's Server Hardware. There should be a NetworkInterface correspondent to each device at ServerHardware's 'portMap'. The device deviceNumber should be used as NetworkInterface ID.

**Comment by ffdarkpenguin** [comment]
As discussed in the chat, will be mapped devices with phisicalPorts of type Ethernet, FibreChannel and Infiniband
