### ISSUE TITLE
Implement NetworkAdapter

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#122]
As oneview-redfish-user, I access "/redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapters/\<deviceNumber\>" and receive a NetworkAdapter object associated with this device at OneView's Server Hardware. The implementation show be as follow:
* there should be one NetworkAdapter for  each NetworkInterface object. Both are mapped to a single network device at OneView. 
* in the property NetworkPorts, there should be a link to a collection of NetworkPorts
* there should be an array of Controllers with a single Controller inside containing the number of physical ports available and number of device functions (how many virtual ports are there for a single physical port) on controllerCapabilities object
* also on the single controller, in the Links property, there should be a NetworkPorts filled with an array of NetworkPort objects and a NetworkDeviceFuncions with an array of NetworkDeviceFunction objects.

**Comment by ffdarkpenguin** [comment]
Added a s to NetworkAdatper at the url:
 "/redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapter/<deviceNumber>"
now it is:
 "/redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapters/<deviceNumber>"

**Comment by ricardoas** [comment]
An example of a NetworkAdapter can be found [here](http://etherpad.lsd.ufcg.edu.br/p/NetworkAdapter)
