### ISSUE TITLE
Implement NetworkDeviceFunction

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#124]
As oneview-redfish-user, I access "/redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapters/\<deviceId\>/NetworkDeviceFunctions/\<id\>" and receive a NetworkDeviceFunction object associated with this adapter, one for each 3-tuple (physical_port, virtual_port, port_function). The ID should be the concatenation of each element id separated by "_". The NetworkDeviceFunction capabilities can be collected from OneView ServerHardwareType.

**Comment by ffdarkpenguin** [comment]
Added a "s" to NetworkDeviceFunction in the URL:
 /redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapters/<deviceId>/NetworkDeviceFunction/<id>
now it is:
/redfish/v1/Chassis/<server_hardware_uuid>/NetworkAdapters/<deviceId>/NetworkDeviceFunctions/<id>
