### ISSUE TITLE
Implement NetworkDeviceFunctionCollection

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#125]
As oneview-redfish-user, I access "/redfish/v1/Systems/<server_hardware_uuid>/NetworkAdapters/<deviceId>/NetworkDeviceFunctions" and receive the collection of NetworkDeviceFunctions objects associated with this adapter, one for each 3-tuple (physical_port, virtual_port, port_function). The ID should be the concatenation of each element id separated by "_".

**Comment by ffdarkpenguin** [comment]
I'm assuming that the correct URL is /redfish/v1/Systems/<server_hardware_uuid>/NetworkAdapters/<DEVICE_ID>/NetworkDeviceFunctions
Note: added DEVICE_ID to the URL
