### ISSUE TITLE
Perform schema validation resolving $ref locally

### ISSUE THREAD

**Issue by ffdarkpenguin** [HewlettPackard/oneview-redfish-toolkit#135]
Currently the jsonschema validation lib resolves all $ref to DMTF website and download the schemas from that website to complete the validation. We need to find a way for it to refer to files locally available and not use Internet access to download the files.

**Comment by ricardoas** [comment]
As oneview-redfish-toolkit developer, I am able to run tests without needing external internet access to JSON schema validation.

**Comment by ricardoas** [comment]
Scenario #1: local only
schema_dir=local_dir
ServiceRoot = ServiceRoot.v1_3_0.json

Fast fail before service starts if cannot find files.

**Comment by ricardoas** [comment]
We discovered that jsonschema lib can resolve schemas locally if build with an already filled initial cache, i.e. building a [RefResolver](https://python-jsonschema.readthedocs.io/en/latest/references/) with local cache information on *store* parameter. This local cache is afaik a dictionary with a URL as key and the JSON schema content as value.

Using this local cache parameter, we do NOT need to modify DMTF schemas to resolve them locally; we do not need to keep providing a remote-dependant solution; the version at the repository is ready to run with a folder containing the latest supported (and tested) version of DMTF's schemas; and, finally, the user can change the content of this folder at will as long as the files pointed at *\[schemas\]* section of redfish.conf exists in the schema folder configured at *schema_dir*.

According to what has been discussed on Nov 14th meeting, the scenario we are aiming for in this User Story is:
* As oneview-redfish-toolkit user, I am able to run the service using validation of JSON responses using DMTF's original schemas placed in *schema_dir* local folder and schema versions pinned at *\[schemas\]* section at redfish.conf file.

**Comment by ricardoas** [comment]
Running with conformance check to ensure everything is available locally before merging!
