### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#14]
As a code reviewer, I access a report on the results of unit/functional tests and pep8 verification for each submitted commit/PR.

**Comment by ricardoas** [comment]
We can use https://github.com/HewlettPackard/python-hpOneView/blob/master/.travis.yml as a model, enabling to python 3.5 though.

I also think we need special privilege to enable travis at: https://travis-ci.org/HewlettPackard/oneview-redfish-toolkit (would you mind taking a look at that, @bsoutham ? If you open this logged in with you github account an "activate" button should appear as far as I remember...)

**Comment by bsoutham** [comment]
travis-ci has been enabled on the repo
