### ISSUE TITLE
Implement a Flask receiver

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#15]
As oneview-redfish-toolkit user, I launch a flash service in a given port that answers a hellow world request. An equivalent test show be provided verifying the return code and content.

**Comment by ricardoas** [comment]
I tried out using a recent iLO from one of our C7000 blades and I noticed that if we issue a request to "http://host_url/redfish" it answers with`:
```
{  
   "v1":"/redfish/v1/"
}
```
Can we use this as a hello world????

**Comment by llvieira** [comment]
Yes, we can use this as a Hello World. I'll send this update.
