### ISSUE TITLE
Tox should not be  running the start script

### ISSUE THREAD

**Issue by ffdarkpenguin** [HewlettPackard/oneview-redfish-toolkit#155]
While running tox the it's calling the start script. If the conf have a valid OneView configuration it will start the flask server and will stop running tox.
When the configuration is not valid the following error appear in the output
IMO should not be calling the start script.
2017-11-01 14:33:48,087 - root - ERROR - Failed to load app configuration
2017-11-01 14:33:48,087 - root - ERROR - Failed to connect to OneView: Failure during login attempt.

**Comment by ricardoas** [comment]
This is also happening on docs generation. My guess is that as python tries to import the file it runs the start up because it is not being triggered by a `__main__` function.

**Comment by ffdarkpenguin** [comment]
http://www.sphinx-doc.org/pt_BR/stable/man/sphinx-apidoc.html
