### ISSUE TITLE
Add adapter info on NetworkDeviceFunction

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#158]
Use info from Server Hardware Type's adapter for FibreChannel type.

**Comment by ffdarkpenguin** [comment]
FibreChannel ports don't show virtual ports (aka DeviceFunctions) on OneView DCS I'm using. In a discussion with @danielreed he is confident that it wont have. In this case this US should be rejected. 
If in fact exists DeviceFunctions for FibreChannel I need a sample SH json to implement this. 
So this is blocked to PO provide a SH json with FibreChannel with DeviceFunctions or to close this without changes.
