### ISSUE TITLE
Does OneView resources implement eTags?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#160]
Check if ServerHardware, Enclosure and Rack return eTag information that can be used to mark redfish equivalent resources. If so, implement this as a header on the responses. It should be on the format: ETag: W/"\<string\>" according to [the specification](http://redfish.dmtf.org/schemas/DSP0266_1.1.html#etags)

**Comment by adriane-cardozo** [comment]
We can get eTag from the object returned by Python SDK, e.g. server_hardware['eTag'], enclosure['eTag'], racks['eTag].
