### ISSUE TITLE
Enable/disable session based authetication

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#184]
As oneview-redfish-toolkit user, I have a new parameter at redfish.conf file named "authentication_mode", whose possible values are conf (default value) or session. If set to "conf", hpOneView client session should be instantiated using credentials from redfish.conf as it is currently done. Otherwise, a new hpOneView client session should be created for each received request using a token at "x-auth-token" header for each request. In this mode, the request should fail if the token is invalid. System Root should be accessible without authentication.

**Comment by ffdarkpenguin** [comment]
Depends on 165 implemented

**Comment by llvieira** [comment]
#165 is ready!
