### ISSUE TITLE
Implement ComputerSystemCollection

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#20]
As oneview-redfish-toolkit user, I access "/redfish/v1/Systems" and receive info from available ComputerSystems in the OneView. The referenced ComputerSystem resources should point to a URL in the format "/redfish/v1/Systems/<server_hardware_uuid>".

**Comment by ffdarkpenguin** [comment]
@ricardoas URI are case sensitive, I think it should only be Systems

**Comment by ffdarkpenguin** [comment]
On DMTF mockups :
Not Found

The requested URL /redfish/v1/systems/ was not found on this server.

**Comment by ricardoas** [comment]
Thanks! Updated the description
