### ISSUE TITLE
How are HPE OneView event types structured?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#201]
How are events organized at HPE OneView resource model and how can they be mapped to [Redfish schema](https://redfish.dmtf.org/schemas/Event.v1_2_1.json)?

Check [python-hpOneView](https://github.com/HewlettPackard/python-hpOneView/tree/master/examples/scmb) example code to connect to SCMB and receive events.

**Comment by ffdarkpenguin** [comment]
How should I respond to this? Here, in a TXT doc, in MD doc?

**Comment by ricardoas** [comment]
Well... at least a comment here should be enough. The goal here is to answer:

1. Does each OneView event type matches one Redfish event type?
1. Can we use a single class to map them or we need a hierarchy?
1. Which SCMB queues should we subscribe to?

**Comment by ricardoas** [comment]
From the last meeting's discussion:
* for `ResourceUpdated`, `ResourceAdded` and `ResourceRemoved`: subscribing to `scmb.*.Created.#` in order to get all resource creation, for example, will result in receiving a lot of undesired events for Alert and Tasks resources among others. Our best idea is to subscribe to each OneView resource of interest independently, i.e.; subscribing to `scmb.server-hardware.Created.#`, `scmb.enclosure.Created.#`, `scmb.rack.Created.#`, and so on.
* for `Alert`: subscribing to `scmb.alert.#` and then filtering by the associated resources of interest is the best plan to this kind of event.
* for `StatusChange`: we have not yet identified which SCMB topic will lead to this events, see #226 for more info.

**Comment by adriane-cardozo** [comment]
https://github.com/HewlettPackard/oneview-redfish-toolkit/blob/master/oneview_redfish_toolkit/api/scmb.py
