### ISSUE TITLE
How subscriptions are made at redfish Event Service: per resource?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#202]
Single subscription per appliance or one per resource? Check Redfish [specification](http://redfish.dmtf.org/schemas/DSP0266_1.1.html) and [schema](https://redfish.dmtf.org/schemas/EventService.v1_0_6.json).

**Comment by llvieira** [comment]
According to the spec and based on what @joehandzik said, subscriptions are made per `EventService`, and you could actually have multiple subscriptions against a single `EventService` (like if you wanted to route `EventService` notifications into both a Slack and an email endpoint). The `EventService` is always located at the `ServiceRoot` ("The `EventService` is found off of the Service Root as described in the Redfish Schema for that service"), so it will listen for events on anything that is under the `ServiceRoot` as well.

Based on the following Redfish mockup, @joehandzik explains:

https://redfish.dmtf.org/redfish/mockups/v1/842

"The `EventService` is located at the `ServiceRoot` for this server (and it's located there for all the other examples that it's present for, too). So based on that, I think you're safe to assume that the `EventService` will listen for events on anything that is also underneath that `ServiceRoot`. I assume it'd be possible for us to implement `EventServices` on a per-resource level too (like if you decided that you didn't want to listen for disk events but really want network events), but that doesn't seem to be how we're mocking anything up today."

Thank you so much, @joehandzik. :+1:

**Comment by joehandzik** [comment]
@llvieira Happy to help! Let me know if something doesn't work right and I'll get you the right contacts to help if I can't.

**Comment by llvieira** [comment]
OK @joehandzik, we'll keep in touch. Thank you again! :smile:

**Comment by ricardoas** [comment]
Thanks you very much for helping, @joehandzik! We really appreciate that...

I guess we have now a good idea of what we're aiming for, right, @llvieira? I added new issues to specific endpoints to implement... can you take a look on them and see if they're ok with this discussion?

**Comment by llvieira** [comment]
Exactly @ricardoas. I looked at them and it sounds good for me.
