### ISSUE TITLE
Get EventService

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#211]
As oneview-redfish-toolkit user, I send a GET request to "/redfish/v1/EventService/" and I receive a JSON containing the main configuration for the EventService.

**Comment by ricardoas** [comment]
An example of the returned JSON can be found [here](https://gist.githubusercontent.com/ricardoas/2bd9f36b338edb0de5a2427e2ea13097/raw/a367842adab682382f723db9d01d55694232974b/eventservice.json). Can you take a look on these attributes meaning (at the spec) a compile a list of which of them we should load from the config file?

**Comment by llvieira** [comment]
@ricardoas, I took a look on that, and as result:

- `Status`: We need to decide how to find this information. Currently this information is hard-coded in our code.

- `DeliveryRetryAttempts` [**Load from config file**]: The value of this property shall be the number of retrys attempted for any given event to the subscription destination before the subscription is terminated.

- `DeliveryRetryIntervalSeconds` [**Load from config file**]: The value of this property shall be the interval in seconds between the retry attempts for any given event to the subscription destination.

- `SubscriptionRemovalAction` [**???**] = I don't figure out this information on the schema.

- `SubscriptionRemovalTimeIntervalInMinutes`  [**???**] = I don't figure out this information on the schema.

The key `DeliveryRetryIntervalInSeconds` in the example has a different name on the schema. In `EventService.v1_0_4.json` the name for this key is: `DeliveryRetryIntervalSeconds`.

All other keys are hard-coded.

**Comment by ricardoas** [comment]
Well... from that I think we can:
* set DeliveryRetryAttempts and DeliveryRetryIntervalSeconds with values loaded from redfish.conf;
* ignore SubscriptionRemoval* fields from this JSON example as we did't find it in the spec nor in the schemas;
* Type and links are pretty straightforward for me... the former contains the name of the schema; while the latter contains two links: one for this object itself and the other for Subscription collections, right?

**Comment by ricardoas** [comment]
Update: Type and Links are also not available on the schema! We should drop them too...

**Comment by llvieira** [comment]
Yeah, they are not available! ;)
