### ISSUE TITLE
Add TestEvent Action

### ISSUE THREAD

**Issue by reinaldo-ufcg** [HewlettPackard/oneview-redfish-toolkit#215]
As oneview-redfish-toolkit user interested in using EventService, I am able to test my event callback server by submitting a POST request to "EventService/Actions/EventService.SubmitTestEvent" triggering a test event to all subscribed users.

**Comment by ricardoas** [comment]
Since we're using EventService.v1_0_4.json, there is no need for the user to specify each event parameter, we should fill the mandatory ones with fake info.

**Comment by ricardoas** [comment]
[Redfish-Event-Listener](https://github.com/DMTF/Redfish-Event-Listener) can be used as an event listener.
