### ISSUE TITLE
GET on NetworkInterface/<id> returns 404

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/oneview-redfish-toolkit#223]
Doing a GET on Systems/\<id\>/NetworkInterface/\<id\> results in a 404.  There's nothing useful in the log.

**Comment by ricardoas** [comment]
Thansk, @danielreed !
The correct endpoint should is "/Systems/\<id\>/NetworkInterfaces/\<id\>" but NetworkInterfacesCollection is listing with a missing 's'...

PS: I agree that the logging is not that used when the URL does not match any of the implemented endpoints. My guess is that we can customize that for the whole flask app...

**Comment by ricardoas** [comment]
Here: https://github.com/HewlettPackard/oneview-redfish-toolkit/blob/master/oneview_redfish_toolkit/api/network_interface_collection.py#L51 !!!
