### ISSUE TITLE
Flask running in debug mode

### ISSUE THREAD

**Issue by lhsvobodaj** [HewlettPackard/oneview-redfish-toolkit#236]
As can be seen in the [app.py](https://github.com/HewlettPackard/oneview-redfish-toolkit/blob/master/oneview_redfish_toolkit/app.py), there is no option to run the app with the debug mode disabled.

An alternative would be to add a configuration option in the `redfish.conf` file, so the user can decide whether to run in debug mode or not.

**Comment by llvieira** [comment]
It sounds great, @lhsvobodaj! :grinning:
