### ISSUE TITLE
Implement ResourceBlock for Server Hardware

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#250]
one ResourceBlock for Server Hardware. Map processor and memory information.

Processors[]:
- For each Processor:
  - TotalCores: "ov processorCoreCount"
  - ID: incremental number
  - MaxSpeedMHz: "ov processorSpeedMhz"
  - ProcessorType: CPU

Memory[]:
- ID: 1
- Name: "Memory"
- CapacityMiB: "ov memoryMb"

Response from OV:
  "powerState": "On",
  "processorCoreCount": 4,
  "processorCount": 2,
  "processorSpeedMhz": 2400,
  "processorType": "Intel(R) Xeon(R) CPU E5620 @ 2.40GHz", 
  "memoryMb": 1048576

**Comment by lhsvobodaj** [comment]
About the memory capacity field, according to OneView REST API reference documentation, the value reported in the REST API is already in MiB:

> memoryMb: Amount of memory installed on this server hardware in MiB (1 MiB = 1,048,576 bytes).

**Comment by lhsvobodaj** [comment]
The allowable state values for server hardware are:

- Unknown (not initialized)
- Adding (server being added)
- **NoProfileApplied (server successfully added) --> Unused**
- Monitored (server being monitored)
- Unmanaged (discovered a supported server)
- Removing (server being removed)
- RemoveFailed (unsuccessful server removal)
- Removed (server successfully removed)
- **ApplyingProfile (profile being applied to server) --> Composing**
- **ProfileApplied (profile successfully applied) --> Composed** 
- RemovingProfile (profile being removed)
- **ProfileError (unsuccessful profile apply or removal) --> Failed**
- Unsupported (server model or version not currently supported by the appliance)
- UpdatingFirmware (server firmware update in progress)

Values in use by the toolkit are the ones in bold.
