### ISSUE TITLE
Update Status for Computer System Resource Block and for Composed System based on Oneview response

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#296]
Status should be updated according to Oneview states. State can be different from "Enabled".

The allowable state values for server hardware are:

Unknown (not initialized) --> null
Adding (server being added)
NoProfileApplied (server successfully added) --> Unused
Monitored (server being monitored)
Unmanaged (discovered a supported server)
Removing (server being removed)
RemoveFailed (unsuccessful server removal)
Removed (server successfully removed)
ApplyingProfile (profile being applied to server) --> Composing
ProfileApplied (profile successfully applied) --> Composed
RemovingProfile (profile being removed)
ProfileError (unsuccessful profile apply or removal) --> Failed
Unsupported (server model or version not currently supported by the appliance)
UpdatingFirmware (server firmware update in progress)
Values in use by the toolkit are the ones in bold.

**Comment by adriane-cardozo** [comment]
Waiting feedback from Dan/Blaine regarding some mappings and drive status.

**Comment by victorhugorodrigues** [comment]
Mapping Status OneView/Redfish:

[Status OneView Redfish Mapping.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0d6a51af365a0013a0006a/125516c66e82c728ace21e0d46db809b379790e9a0e7ba75ad58e7d41b4323752017ab6b5d84f338b64c7c43434d0eee1e020a17b8eb8339a3bf3a78dc5a59efd0645e70c16e11acb9d017b606b872825d99a4fedb1294b7607caddecd5d340c041f83fe5836a2904dc85af242e94c57b65e.xlsx)

**Comment by adriane-cardozo** [comment]
Let's update the Status for Computer System Resource Block and Status for a Composed System (checking server profile and server hardware).

Out of scope: Status for Storage Resource Block and Network Resource Block.
