### ISSUE TITLE
Get to know redfish specification

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#3]
As a developer, I understand the overall specification and I am able to identify the main components using a mockup available at http://redfish.dmtf.org/

**Comment by ricardoas** [comment]
Interesting video with redfish usage at OpenStack Ironic: 
https://www.openstack.org/videos/video/empowering-ironic-with-redfish-support-1

**Comment by ffdarkpenguin** [comment]
Tested some mockups, evaluated the some schema structure, watched the video. Done for now.
