### ISSUE TITLE
SCMB not working when using API 600

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#328]
authentication_mode set to "conf" stop working when using API 600.
OneView changed certificate_authority API and now toolkit is not able to retrieve certs. 

curl -XGET -L -H "auth:${AUTH}" -H "X-Api-Version:600" -H "Content-Type:application/json" -k https://16.125.77.104/rest/certificates/ca?filter='certType:INTERNAL'

**Comment by Vijayakannan-M** [comment]
#524 - Fixed
