### ISSUE TITLE
Change Oneview Redfish Toolkit to use CherryPy

### ISSUE THREAD

**Issue by sidneifranco** [HewlettPackard/oneview-redfish-toolkit#348]

**Comment by sidneifranco** [comment]
As we have on #324 issue with the result of the investigation, CherryPy was selected to be used as base of Flask. To have it integrated, we have some required changes:
- Change the app.py code to use CherryPy standard;
- Change the way that the config files are defined, changing the installer too;
- Check and change, if required, the logs mechanism;
- Change run.sh to call cherryd to start the service as a daemon;
- Change the requirements.txt adding the cherrypy to be installed.

**Comment by victorhugorodrigues** [comment]
Another point that is needed is:
- Change the way we read the config file properties on application.
