### ISSUE TITLE
Add link to Chassis on Computer System

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#35]
As oneview-redfish-toolkit, I access "/redfish/v1/System/<server_hardware_uuid>" and the info returned contains a link to this ComputerSystem's Chassis (possibly in the form: /redfish/v1/Chassis/<server_hardware_uuid> using the same Server Hardware UUID)

**Comment by ffdarkpenguin** [comment]
The correct form o the link would be a link to the chassis containing it. In the case, it can be 
/Chassis, to list all and the server hardware will be there too or
/Chassis/EnclosureUUID which is the chassis for the given computer system.
I´m implementing the later.
