### ISSUE TITLE
Concurrency for multiple OneView

### ISSUE THREAD

**Issue by victorhugorodrigues** [HewlettPackard/oneview-redfish-toolkit#366]
Handling concurrency for multiple OneView support on:
- Map for Redfish -> OneView authentication tokens;
- Map for OneView resource -> OneView client.

**Comment by ricardogpsf** [comment]
Maybe we do not have to worry with concurrency for our maps of multiple Oneview, due the GIL of python.
Who is assigned to this task can see more about this [here](https://opensource.com/article/17/4/grok-gil), for example.
After read about, let us know if is necessary keep this task.
