### ISSUE TITLE
Add support for Description in Composed system and Capabilities Object

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#387]
Add Description attribute in the Computer System resource.
Depends on #370

**Comment by adriane-cardozo** [comment]
Add Description in the Capabilities as optional (check spec)

**Comment by victorhugorodrigues** [comment]
For CapabilitiesObject add Description with following annotations:
"Description@Redfish.OptionalOnCreate": true, 
"Description@Redfish.UpdatableAfterCreate": true

**Comment by adriane-cardozo** [comment]
Depends on #370
