### ISSUE TITLE
Get to know python-ilorest-library

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#4]
As a developer, I'll query the main components using python-ilorest-library to a single Server Hardware

**Comment by danielreed** [comment]
We aren't going to be querying the iLO for this project.  All of the information we gather will come directly from the OneView API.

**Comment by ricardoas** [comment]
I got that... I just added this because, as we only have C7000 hardware available at UFCG, I thought it would be a cool thing for @llvieira to query the BLs servers iLO using this redfish client api to get a real feeling of how http://redfish.dmtf.org/redfish/v1/mockup/840 json are in a real environment with real info...
