### ISSUE TITLE
Conf mode is requiring auth token

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#414]

**Comment by victorhugorodrigues** [comment]
I just pushed a remote branch with a quick fix, it should be simple to solve, but once I could not test the fix for some sintax error, it should be tested. It could help @ricardogpsf to create the fix.

**Comment by victorhugorodrigues** [comment]
the branch is: fix/conf_mode_multiple_ov
