### ISSUE TITLE
Route Chassis request depending on OneView resource

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#43]

**Comment by danielreed** [comment]
I think we can use a query against the Index Service to figure out our route into OneView.  So we could do something like:

/rest/index/resources?filter=uuid=<uuid>

This will return an array of members but the Resource in the array will have a category (ie server-hardware or enclosures) that we can use to build our route.

**Comment by ricardoas** [comment]
I could not find this mapped into hpOneView, so I opened [an issue](https://github.com/HewlettPackard/python-hpOneView/issues/312) asking for help... :D

**Comment by ricardoas** [comment]
Hey @danielreed... a new hpOneView version with the index resource implementation has just been published. Are you going to implement this routing or is this card just related to the investigation?
