### ISSUE TITLE
Cherrypy configuration and performance analysis

### ISSUE THREAD

**Issue by adriane-cardozo** [HewlettPackard/oneview-redfish-toolkit#431]
- Computer System Collection (check scaling parallel requests)

**Comment by adriane-cardozo** [comment]
👍

**Comment by victorhugorodrigues** [comment]
As soon as  we get a real OneView instance we can run our performance tests again. Closing issue.

Including performance test logs as attachments:
[ConcurrentPerformance3.xlsx](https://github.com/HewlettPackard/oneview-redfish-toolkit/files/2394100/ConcurrentPerformance3.xlsx)
 [report_toolikt_dcs_saturation.txt](https://github.com/HewlettPackard/oneview-redfish-toolkit/files/2394105/report_toolikt_dcs_saturation.txt)
[report_single_dcs_call.txt](https://github.com/HewlettPackard/oneview-redfish-toolkit/files/2394106/report_single_dcs_call.txt)
[report_dcs_saturation.txt](https://github.com/HewlettPackard/oneview-redfish-toolkit/files/2394107/report_dcs_saturation.txt)
[report_dcs_saturation_2.txt](https://github.com/HewlettPackard/oneview-redfish-toolkit/files/2394108/report_dcs_saturation_2.txt)
