### ISSUE TITLE
Get to know flask

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#5]
As a developer, I'll be able to bootstrap a new project using python flask framework

**Comment by llvieira** [comment]
To a large application, it's necessary to divide it into smaller applications, and one of the best ways to do it on the Flask I've found is using **Blueprints**.

The **Blueprint** acts like a modular reflection of the main application, in other words is a object that works similarly to a Flask object, sharing the same resources and allowing us to build modular applications that separate responsibilities into different files. 

For more information about it we can consult the pretty comprehensive Flask documentation at: [http://flask.pocoo.org/docs/0.12/blueprints/#blueprints](http://flask.pocoo.org/docs/0.12/blueprints/#blueprints)
[http://flask.pocoo.org/docs/0.12/patterns/packages/](http://flask.pocoo.org/docs/0.12/patterns/packages/) -- in the end of this page

**Comment by ffdarkpenguin** [comment]
Created a hello world. moving this to Backlog for further investigation. Will prioritize checking the python object schema modules.

**Comment by llvieira** [comment]
Okay @ffdarkpenguin
