### ISSUE TITLE
error creating 2 server at the same time from VCF SDDC manager

### ISSUE THREAD

**Issue by fabienbrami** [HewlettPackard/oneview-redfish-toolkit#543]
. If you compose new server hardware through SDDC manager from a particular template and you choose quantity >= 2, then the second server profile creation will fail. Because redfish uses always the same name for JBOD creation, in this case “Storage 1” for the first JBOD and “Storage 2” for the second JBOD.
 

If you compose the server hardware one by one (sequential) this error did not appear because OneView adds some random numbers to the JBOD names if they already exist.

**Comment by Vijayakannan-M** [comment]
This is fixed in the below commit.

#564 - Fix for logger exception and concurrent compose request

https://github.com/HewlettPackard/oneview-redfish-toolkit/commit/36bdd71e3cf6e0ecc327a3515714f860da6a2455
