### ISSUE TITLE
Service call to the translation layer has failed. Reason: [ 403 FORBIDDEN ]

### ISSUE THREAD

**Issue by clmuelle001** [HewlettPackard/oneview-redfish-toolkit#549]
Hello! I did not find anything regarding this progress message when starting a compose job. Maybe there are issues with the certificates? But "sos" tool from sddc is green...

Additional infos from the sddc task:

Cause:
Type: com.vmware.vcf.composability.exception.ComposabilityRestException
Message: 403 FORBIDDEN

Type: org.springframework.web.client.HttpClientErrorException
Message: 403 FORBIDDEN 

Any ideas what to do?

Best regards
Claus

**Comment by Vijayakannan-M** [comment]
The selected server hardware resource was not "OK" state to consume. We are sending the right to error message to SDDC manger. But they converting into custom exception. NO fix required. You can check toolkit log if you need more detail about error.
