### ISSUE TITLE
Can we generate/validate Python code from Redfish JSON schemas?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#7]

**Comment by ffdarkpenguin** [comment]
Found this tool on DTMF github. 
https://github.com/DMTF/Redfish-Tools/blob/master/csdl-to-json-convertor/service.py
It converts files fom CSDL to JSON format. 
I read the code but and I noticed that function generate_json(url, directory, args):
maybe while mounting the json creates a dictionary. It this enough for you Daniel?

**Comment by danielreed** [comment]
@ffdarkpenguin I'll have to look at that.  Thanks.

**Comment by ffdarkpenguin** [comment]
@danielreed, never mind Daniel, Ricardo shared the module you found that transform a schema in class. That's what you wanted and found. We just need to find/fix the bugs you commented. Can you please share those info here?

**Comment by danielreed** [comment]
Probably should close this issue, the approach is not going to work for this project.
