### ISSUE TITLE
Change Error messages for ManagerCollection

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#80]
As oneview-redfish-toolkit user, I receive a well-known Error response object for all error conditions I may encounter related to Manager  collection operations.

**Comment by ffdarkpenguin** [comment]
So far most of our error are either 404 or 500.
For 500 error we have an InternalServer error option in redfish error list. 
But for 404 it does not exist.
Should I keep returning just 404 as it is now when the resource is not found and add the new class json  only for 500 errors?
If you want a specific error for 404, please  add to issue #80 how it should be done.
I could not found anything to reply to 404

**Comment by ricardoas** [comment]
In this particular case, seeing from available error codes on the spec, I think we should provide:

code | meaning | situation
------|-----------|----------
200 OK | The request was successfully completed and includes a representation in its body. | Successful case
503 Service Unavailable | The server is currently unable to handle the request due to temporary overloading or maintenance of the server. | All other situation: OneView could not be reched, raised an exception, ManagerCollection did not pass the validation

**Comment by ffdarkpenguin** [comment]
Do you want all error we mapped 500 (internal server error) to be changed to 503???
An OV error is not a server overloaded or in maintenance IMHO
it´s an internal server error that won't be solved if someone don't fix something
And I didn't understand the reference to the 200 code. Are you asking to build the OK reply message on this cases???

**Comment by ricardoas** [comment]
Agreed! Fixed the table above...

**Comment by ffdarkpenguin** [comment]
Still have a problem: should I create the message object for 200 response??? This does not makes sense to me, unless it's an action. By the table I should be creating those... at least it's what I understand from the table

**Comment by ffdarkpenguin** [comment]
General solution:
Code 200: don't generate a an error object
Code 404: Generate a json with code GeneralError and message saying that the resournce (CS, Enclousre, etc) was not found and empty extended info
Code 500: Generate a json with code InternalError and one extended info with Internal error
Action error: same behave as 500 error, but filled with the error code specific to the error
