### ISSUE TITLE
Run conformace check

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#81]
As oneview-redfish-toolkit user, I receive a report on the completeness of the redfish API coverage by running Redfish Service Conformance Check Tool against a service instance configured with OneView + DCS

**Comment by ricardoas** [comment]
Tool available at: https://github.com/DMTF/Redfish-Service-Conformance-Check

**Comment by ffdarkpenguin** [comment]
Please see attached a cookbook with steps to run the conformance test tool against our system and also the result of running it against the latest merged version at 12:48h 2017-09-27
[DMTF-ConfomanceCheck-Cookbook.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984cbec060570001fb4320d/125516c66e82c728ace21e0d46ccb9ae05cfa0a681efb04ea553f3910a4e2270224980247f8ee127b049394d4d1f0cf31b0d0c00eef39b2eafb034268c0e09ecd86c5b73953d11adea8a16b803e829995397f4edd4189fb5646fb2c99d452c1f021288fa5d33a59a4ccd51f14fe24e47e9.txt)
[redfish-assertions.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984cbec060570001fb4320d/125516c66e82c728ace21e0d46fa919e258b90a1c2e8ac50a14fe49d264834316546b3397f8fe62bab0021435a5648a4175e0d46fdf0882fa1e53c708b0e03e4d66f0d7dd42103eee9dc4be05ce36ade0d97bcae884ccae93825e18e8c483b17021c8cfc4f78.xlsx)

**Comment by ffdarkpenguin** [comment]
requires HTTPs to work

**Comment by ffdarkpenguin** [comment]
Required /redfish/v1/odata to work

**Comment by ffdarkpenguin** [comment]
Attached TXT file with cookbook to configure the tool
[DMTF-ConfomanceCheck-Cookbook.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984cbec060570001fb4320d/125516c66e82c728ace21e0d46ccb9ae05cfa0a681efb04ea553f3910a4e2270224980247f8ee127b049394d4d1f0cf31b0d0c00eef39b2eafb034268c0e09ecd86c5b73953d11adea8a16b803e829995397f4edd4189fb5646fb2c99d452c1f021288fa5d33a69c4bcf5efe4ce14f47e9.txt)

**Comment by ffdarkpenguin** [comment]
Running the tests worked fine for around 42 min and then it froze. Attached the XLSX and a TXT log with what as output to screen
[20170928-193810_rf-assertions-run.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984cbec060570001fb4320d/125516c66e82c728ace21e0d46bac4cb74d2dafbd7a4ee1af705a1c41654213e2817b02e6291ea27b15136131a015cb053181d1ba6acda6fb4bc2e75835a03bbd73f5d75cf3c15abeb821fbe53b2298c4dd7bfae965e82b96371b8d6d6056b5c17129bfe543fa19c4bce5ef34ae14d5da6153e71ab.xlsx)
[ConfCheckLog.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984cbec060570001fb4320d/125516c66e82c728ace21e0d46cb9b9425a18bac8ce2934ca31fbcd6395428792c07b7692ac7b671e91a7d570d5d4fa5405c5817fcf98879aebf3b72d85519f1c32f0e2a92624cf5f2d75dad0ba821824584b3bc8c4ac5e93d25ef8989472c53.txt)

**Comment by ffdarkpenguin** [comment]
Apart from freezing the toll works minimally for us to start fixing our mistakes. But it requires the depending issues to be merges (HTTPS support and odata endpoint). Closing this issue on my part
