### ISSUE TITLE
Perform PowerOps for ComputerSystem

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#82]
As oneview-redfish.toolkit user, I perform a POST request at "/redfish/v1/System/<server_hardware_uuid>/Actions/
ComputerSystem.Reset" with one of the allowed values for ResetType and the action is performed on the correspondent HPE OneView Server Hardware

**Comment by llvieira** [comment]
I think that a **PUT** request makes more sense, as the user will replace an existing data.
